import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const VerificationForm = () => {
  const [proposal, setProposal] = useState(
    "AI-generated recommendation proposal."
  );
  const [isEditable, setIsEditable] = useState(false);
  const navigate = useNavigate();
  const location = useLocation();

  // Extract the 'source' parameter from the URL
  const source = new URLSearchParams(location.search).get("source");

  const handleSubmit = () => {
    if (source === "request") {
      navigate("/waitingpage"); // Redirect to the waiting page
    } else if (source === "create") {
      navigate("/confirmationpage"); // Redirect to the confirmation page
    }
  };

  const handleShare = () => {
    const url = window.location.href;
    alert(`Share this URL: ${url}`);
  };

  return (
    <div className="min-h-screen bg-gray-100">
      {/* Navbar */}
      <Navbar />

      {/* Header Section */}
      <header className="bg-[#2f2f2f] text-white py-20">
        <div className="container mx-auto text-center">
          <h1 className="text-4xl font-extrabold mb-4">
            Recommendation Verification
          </h1>
          <p className="text-lg mb-8">
            Here is the recommendation proposal generated by our AI assistant.
            You can edit it before submitting.
          </p>
          <p className="text-lg mb-8">
            Please verify if this recommendation aligns with your needs before
            submitting it. If you need to make changes, feel free to do so.
          </p>
        </div>
      </header>

      {/* Main Content */}
      <main className="bg-[#4f4f4f] text-gray-800 py-12">
        <div className="container mx-auto px-6">
          <section className="mb-12">
            <div className="bg-[#3a3a3a] p-8 rounded-lg shadow-lg">
              <h3 className="text-2xl text-white font-semibold mb-6">
                Recommendation Proposal
              </h3>
              <textarea
                value={proposal}
                onChange={(e) => setProposal(e.target.value)}
                disabled={!isEditable}
                className="w-full mt-4 p-6 bg-gray-300 text-gray-700 rounded-lg shadow-md focus:outline-none focus:ring-2 focus:ring-blue-400"
                rows="6"
              />
            </div>
          </section>

          {/* Buttons aligned on the same line */}
          <section className="flex justify-center space-x-6 mb-12">
            <button
              onClick={handleShare}
              className="bg-blue-500 text-white px-8 py-4 rounded-full hover:bg-blue-600 transition-all"
            >
              Share this Proposal
            </button>
            <button
              onClick={() => setIsEditable(!isEditable)}
              className="bg-orange-500 text-white px-8 py-4 rounded-full hover:bg-orange-600 transition-all"
            >
              {isEditable ? "Lock" : "Edit"}
            </button>
            <button
              onClick={handleSubmit}
              className="bg-violet-500 text-white px-8 py-4 rounded-full hover:bg-violet-600 transition-all"
            >
              Submit Recommendation
            </button>
          </section>
        </div>
      </main>

      {/* Footer */}
      <Footer />
    </div>
  );
};

export default VerificationForm;
